class BankData {
  BankData({this.key = '', this.name = '', this.logo = ''});

  String key;
  String name;
  String logo;

  static List<Map<String, BankData>> banks = <Map<String, BankData>>[
    gydxsyyh, // 国有大型商业银行
    gfzsyyh, // 股份制商业银行
    cssyyh, // 城市商业银行
    wzfryh // 外资法人银行
  ];
  static Map<String, BankData> cssyyh = <String, BankData>{
    "MTBANK": BankData(
        key: 'MTBANK',
        name: '浙江民泰商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/MTBANK.png'),
    "RBOZ": BankData(
        key: 'RBOZ',
        name: '珠海华润银行',
        logo: 'assets/keep_accounts/bank/cssyyh/RBOZ.png'),
    "LZBANK": BankData(
        key: 'LZBANK',
        name: '兰州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LZBANK.png'),
    "QLBANK": BankData(
        key: 'QLBANK',
        name: '齐鲁银行',
        logo: 'assets/keep_accounts/bank/cssyyh/QLBANK.png'),
    "GZCB": BankData(
        key: 'GZCB',
        name: '广州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/GZCB.png'),
    "SXCB": BankData(
        key: 'SXCB',
        name: '绍兴银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SXCB.png'),
    "BOCY": BankData(
        key: 'BOCY',
        name: '朝阳银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOCY.png'),
    "FXCB": BankData(
        key: 'FXCB',
        name: '阜新银行',
        logo: 'assets/keep_accounts/bank/cssyyh/FXCB.png'),
    "KELBANK": BankData(
        key: 'KELBANK',
        name: '库尔勒银行',
        logo: 'assets/keep_accounts/bank/cssyyh/KELBANK.png'),
    "LSCCB": BankData(
        key: 'LSCCB',
        name: '乐山市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LSCCB.png'),
    "FJHXBC": BankData(
        key: 'FJHXBC',
        name: '福建海峡银行',
        logo: 'assets/keep_accounts/bank/cssyyh/FJHXBC.png'),
    "YTBANK": BankData(
        key: 'YTBANK',
        name: '烟台银行',
        logo: 'assets/keep_accounts/bank/cssyyh/YTBANK.png'),
    "BOP": BankData(
        key: 'BOP',
        name: '平顶山银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOP.png'),
    "BHB": BankData(
        key: 'BHB',
        name: '河北银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BHB.png'),
    "JSB": BankData(
        key: 'JSB',
        name: '晋商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JSB.png'),
    "LJBANK": BankData(
        key: 'LJBANK',
        name: '龙江银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LJBANK.png'),
    "JXBANK": BankData(
        key: 'JXBANK',
        name: '嘉兴银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JXBANK.png'),
    "XJBANK": BankData(
        key: 'XJBANK',
        name: '新疆银行',
        logo: 'assets/keep_accounts/bank/cssyyh/XJBANK.png'),
    "BOSZ": BankData(
        key: 'BOSZ',
        name: '苏州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOSZ.png'),
    "XABANK": BankData(
        key: 'XABANK',
        name: '西安银行',
        logo: 'assets/keep_accounts/bank/cssyyh/XABANK.png'),
    "LZBANK": BankData(
        key: 'LZBANK',
        name: '泸州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LZBANK.png'),
    "NXBANK": BankData(
        key: 'NXBANK',
        name: '宁夏银行',
        logo: 'assets/keep_accounts/bank/cssyyh/NXBANK.png'),
    "CZCB": BankData(
        key: 'CZCB',
        name: '浙江稠州商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CZCB.png'),
    "ZGBANK": BankData(
        key: 'ZGBANK',
        name: '自贡银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ZGBANK.png'),
    "CZBANK": BankData(
        key: 'CZBANK',
        name: '沧州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CZBANK.png'),
    "YQCCB": BankData(
        key: 'YQCCB',
        name: '阳泉市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/YQCCB.png'),
    "YASSYBANK": BankData(
        key: 'YASSYBANK',
        name: '雅安市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/YASSYBANK.png'),
    "SRBANK": BankData(
        key: 'SRBANK',
        name: '上饶银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SRBANK.png'),
    "XJHHBANK": BankData(
        key: 'XJHHBANK',
        name: '新疆汇和银行',
        logo: 'assets/keep_accounts/bank/cssyyh/XJHHBANK.png'),
    "MSBANK": BankData(
        key: 'MSBANK',
        name: '蒙商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/MSBANK.png'),
    "HRXJBANK": BankData(
        key: 'HRXJBANK',
        name: '华融湘江银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HRXJBANK.png'),
    "LSBANK": BankData(
        key: 'LSBANK',
        name: '莱商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LSBANK.png'),
    "NYBANK": BankData(
        key: 'NYBANK',
        name: '广东南粤银行',
        logo: 'assets/keep_accounts/bank/cssyyh/NYBANK.png'),
    "JHCCB": BankData(
        key: 'JHCCB',
        name: '金华银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JHCCB.png'),
    "JZZLBANK": BankData(
        key: 'JZZLBANK',
        name: '焦作中旅银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JZZLBANK.png'),
    "YBCCB": BankData(
        key: 'YBCCB',
        name: '宜宾市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/YBCCB.png'),
    "CDBANK": BankData(
        key: 'CDBANK',
        name: '承德银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CDBANK.png'),
    "JZBANK": BankData(
        key: 'JZBANK',
        name: '晋中银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JZBANK.png'),
    "JSBANK": BankData(
        key: 'JSBANK',
        name: '江苏银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JSBANK.png'),
    "LSBC": BankData(
        key: 'LSBC',
        name: '临商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LSBC.png'),
    "XCBANK": BankData(
        key: 'XCBANK',
        name: '西藏银行',
        logo: 'assets/keep_accounts/bank/cssyyh/XCBANK.png'),
    "CCQTGB": BankData(
        key: 'CCQTGB',
        name: '重庆三峡银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CCQTGB.png'),
    "HRBCB": BankData(
        key: 'HRBCB',
        name: '哈尔滨银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HRBCB.png'),
    "BOYK": BankData(
        key: 'BOYK',
        name: '营口银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOYK.png'),
    "MYSYBANK": BankData(
        key: 'MYSYBANK',
        name: '绵阳商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/MYSYBANK.png'),
    "FDBANK": BankData(
        key: 'FDBANK',
        name: '富滇银行',
        logo: 'assets/keep_accounts/bank/cssyyh/FDBANK.png'),
    "GSBANK": BankData(
        key: 'GSBANK',
        name: '甘肃银行',
        logo: 'assets/keep_accounts/bank/cssyyh/GSBANK.png'),
    "JNBANK": BankData(
        key: 'JNBANK',
        name: '济宁银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JNBANK.png'),
    "QDCCB": BankData(
        key: 'QDCCB',
        name: '青岛银行',
        logo: 'assets/keep_accounts/bank/cssyyh/QDCCB.png'),
    "YNHTBANK": BankData(
        key: 'YNHTBANK',
        name: '云南红塔银行',
        logo: 'assets/keep_accounts/bank/cssyyh/YNHTBANK.png'),
    "ZZBANK": BankData(
        key: 'ZZBANK',
        name: '枣庄银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ZZBANK.png'),
    "ASBANK": BankData(
        key: 'ASBANK',
        name: '鞍山银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ASBANK.png'),
    "LFBANK": BankData(
        key: 'LFBANK',
        name: '廊坊银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LFBANK.png'),
    "JXBANK": BankData(
        key: 'JXBANK',
        name: '江西银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JXBANK.png'),
    "WZBANK": BankData(
        key: 'WZBANK',
        name: '温州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/WZBANK.png'),
    "NDHB": BankData(
        key: 'NDHB',
        name: '宁波东海银行',
        logo: 'assets/keep_accounts/bank/cssyyh/NDHB.png'),
    "QHDBANK": BankData(
        key: 'QHDBANK',
        name: '秦皇岛银行',
        logo: 'assets/keep_accounts/bank/cssyyh/QHDBANK.png'),
    "JINCHB": BankData(
        key: 'JINCHB',
        name: '晋城银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JINCHB.png'),
    "BOD": BankData(
        key: 'BOD',
        name: '东莞银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOD.png'),
    "SNBANK": BankData(
        key: 'SNBANK',
        name: '遂宁银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SNBANK.png'),
    "BOSC": BankData(
        key: 'BOSC',
        name: '上海银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOSC.png'),
    "TLCB": BankData(
        key: 'TLCB',
        name: '浙江泰隆商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/TLCB.png'),
    "HSBANK": BankData(
        key: 'HSBANK',
        name: '衡水银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HSBANK.png'),
    "XMBANK": BankData(
        key: 'XMBANK',
        name: '厦门银行',
        logo: 'assets/keep_accounts/bank/cssyyh/XMBANK.png'),
    "TLBANK": BankData(
        key: 'TLBANK',
        name: '铁岭银行',
        logo: 'assets/keep_accounts/bank/cssyyh/TLBANK.png'),
    "LYBANK": BankData(
        key: 'LYBANK',
        name: '辽阳银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LYBANK.png'),
    "CZBANK": BankData(
        key: 'CZBANK',
        name: '长治银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CZBANK.png'),
    "JLBANK": BankData(
        key: 'JLBANK',
        name: '吉林银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JLBANK.png'),
    "JZBANK": BankData(
        key: 'JZBANK',
        name: '锦州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JZBANK.png'),
    "HNB": BankData(
        key: 'HNB',
        name: '海南银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HNB.png'),
    "XTB": BankData(
        key: 'XTB',
        name: '邢台银行',
        logo: 'assets/keep_accounts/bank/cssyyh/XTB.png'),
    "WFCCB": BankData(
        key: 'WFCCB',
        name: '潍坊银行',
        logo: 'assets/keep_accounts/bank/cssyyh/WFCCB.png'),
    "RZB": BankData(
        key: 'RZB',
        name: '日照银行',
        logo: 'assets/keep_accounts/bank/cssyyh/RZB.png'),
    "WHBANK": BankData(
        key: 'WHBANK',
        name: '乌海银行',
        logo: 'assets/keep_accounts/bank/cssyyh/WHBANK.png'),
    "ZZBANK": BankData(
        key: 'ZZBANK',
        name: '郑州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ZZBANK.png'),
    "JJCCB": BankData(
        key: 'JJCCB',
        name: '九江银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JJCCB.png'),
    "HLDBANK": BankData(
        key: 'HLDBANK',
        name: '葫芦岛银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HLDBANK.png'),
    "SJBANK": BankData(
        key: 'SJBANK',
        name: '盛京银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SJBANK.png'),
    "BOTS": BankData(
        key: 'BOTS',
        name: '唐山银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOTS.png'),
    "GZBANK": BankData(
        key: 'GZBANK',
        name: '贵州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/GZBANK.png'),
    "GHB": BankData(
        key: 'GHB',
        name: '广东华兴银行',
        logo: 'assets/keep_accounts/bank/cssyyh/GHB.png'),
    "QJSSYBANK": BankData(
        key: 'QJSSYBANK',
        name: '曲靖市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/QJSSYBANK.png'),
    "KLB": BankData(
        key: 'KLB',
        name: '昆仑银行',
        logo: 'assets/keep_accounts/bank/cssyyh/KLB.png'),
    "SICHUAN": BankData(
        key: 'SICHUAN',
        name: '四川天府银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SICHUAN.png'),
    "SZSBK": BankData(
        key: 'SZSBK',
        name: '石嘴山银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SZSBK.png'),
    "HKB": BankData(
        key: 'HKB',
        name: '汉口银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HKB.png'),
    "LZCCB": BankData(
        key: 'LZCCB',
        name: '柳州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LZCCB.png'),
    "NJCB": BankData(
        key: 'NJCB',
        name: '南京银行',
        logo: 'assets/keep_accounts/bank/cssyyh/NJCB.png'),
    "DLB": BankData(
        key: 'DLB',
        name: '大连银行',
        logo: 'assets/keep_accounts/bank/cssyyh/DLB.png'),
    "BSCB": BankData(
        key: 'BSCB',
        name: '长沙银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BSCB.png'),
    "SMGJBANK": BankData(
        key: 'SMGJBANK',
        name: '厦门国际银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SMGJBANK.png'),
    "SCB": BankData(
        key: 'SCB',
        name: '四川银行',
        logo: 'assets/keep_accounts/bank/cssyyh/SCB.png'),
    "WHCCB": BankData(
        key: 'WHCCB',
        name: '威海市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/WHCCB.png'),
    "BDBANK": BankData(
        key: 'BDBANK',
        name: '保定银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BDBANK.png'),
    "TACCB": BankData(
        key: 'TACCB',
        name: '泰安银行',
        logo: 'assets/keep_accounts/bank/cssyyh/TACCB.png'),
    "PJBANK": BankData(
        key: 'PJBANK',
        name: '盘锦银行',
        logo: 'assets/keep_accounts/bank/cssyyh/PJBANK.png'),
    "HBC": BankData(
        key: 'HBC',
        name: '湖北银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HBC.png'),
    "TJBANK": BankData(
        key: 'TJBANK',
        name: '天津银行',
        logo: 'assets/keep_accounts/bank/cssyyh/TJBANK.png'),
    "DTBANK": BankData(
        key: 'DTBANK',
        name: '大同银行',
        logo: 'assets/keep_accounts/bank/cssyyh/DTBANK.png'),
    "CDCB": BankData(
        key: 'CDCB',
        name: '成都银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CDCB.png'),
    "UCCB": BankData(
        key: 'UCCB',
        name: '乌鲁木齐银行',
        logo: 'assets/keep_accounts/bank/cssyyh/UCCB.png'),
    "GYCCB": BankData(
        key: 'GYCCB',
        name: '贵阳银行',
        logo: 'assets/keep_accounts/bank/cssyyh/GYCCB.png'),
    "DZBANK": BankData(
        key: 'DZBANK',
        name: '德州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/DZBANK.png'),
    "BODD": BankData(
        key: 'BODD',
        name: '丹东银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BODD.png'),
    "H3CB": BankData(
        key: 'H3CB',
        name: '内蒙古银行',
        logo: 'assets/keep_accounts/bank/cssyyh/H3CB.png'),
    "TZBANK": BankData(
        key: 'TZBANK',
        name: '台州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/TZBANK.png'),
    "QHBANK": BankData(
        key: 'QHBANK',
        name: '青海银行',
        logo: 'assets/keep_accounts/bank/cssyyh/QHBANK.png'),
    "BGB": BankData(
        key: 'BGB',
        name: '广西北部湾银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BGB.png'),
    "JSCJSYBANK": BankData(
        key: 'JSCJSYBANK',
        name: '江苏长江商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/JSCJSYBANK.png'),
    "YKYHBANK": BankData(
        key: 'YKYHBANK',
        name: '营口沿海银行',
        logo: 'assets/keep_accounts/bank/cssyyh/YKYHBANK.png'),
    "BXSSYBANK": BankData(
        key: 'BXSSYBANK',
        name: '本溪市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BXSSYBANK.png'),
    "ZYBANK": BankData(
        key: 'ZYBANK',
        name: '中原银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ZYBANK.png'),
    "NBTSBANK": BankData(
        key: 'NBTSBANK',
        name: '宁波通商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/NBTSBANK.png'),
    "HDBANK": BankData(
        key: 'HDBANK',
        name: '邯郸银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HDBANK.png'),
    "DCCB": BankData(
        key: 'DCCB',
        name: '达州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/DCCB.png'),
    "ZJKCCB": BankData(
        key: 'ZJKCCB',
        name: '张家口银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ZJKCCB.png'),
    "GLBANK": BankData(
        key: 'GLBANK',
        name: '桂林银行',
        logo: 'assets/keep_accounts/bank/cssyyh/GLBANK.png'),
    "BOB": BankData(
        key: 'BOB',
        name: '北京银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOB.png'),
    "CABANK": BankData(
        key: 'CABANK',
        name: '长安银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CABANK.png'),
    "CCHXBANK": BankData(
        key: 'CCHXBANK',
        name: '长城华西银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CCHXBANK.png'),
    "NBCB": BankData(
        key: 'NBCB',
        name: '宁波银行',
        logo: 'assets/keep_accounts/bank/cssyyh/NBCB.png'),
    "DYCCB": BankData(
        key: 'DYCCB',
        name: '东营银行',
        logo: 'assets/keep_accounts/bank/cssyyh/DYCCB.png'),
    "CQBANK": BankData(
        key: 'CQBANK',
        name: '重庆银行',
        logo: 'assets/keep_accounts/bank/cssyyh/CQBANK.png'),
    "BOQZ": BankData(
        key: 'BOQZ',
        name: '泉州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/BOQZ.png'),
    "QSBANK": BankData(
        key: 'QSBANK',
        name: '齐商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/QSBANK.png'),
    "HSBANK": BankData(
        key: 'HSBANK',
        name: '徽商银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HSBANK.png'),
    "ORDOSB": BankData(
        key: 'ORDOSB',
        name: '鄂尔多斯银行',
        logo: 'assets/keep_accounts/bank/cssyyh/ORDOSB.png'),
    "HMSSYBANK": BankData(
        key: 'HMSSYBANK',
        name: '哈密市商业银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HMSSYBANK.png'),
    "HZCB": BankData(
        key: 'HZCB',
        name: '杭州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HZCB.png'),
    "LYBANK": BankData(
        key: 'LYBANK',
        name: '洛阳银行',
        logo: 'assets/keep_accounts/bank/cssyyh/LYBANK.png'),
    "HZBANK": BankData(
        key: 'HZBANK',
        name: '湖州银行',
        logo: 'assets/keep_accounts/bank/cssyyh/HZBANK.png'),
    "FSCB": BankData(
        key: 'FSCB',
        name: '抚顺银行',
        logo: 'assets/keep_accounts/bank/cssyyh/FSCB.png')
  };
  static Map<String, BankData> gfzsyyh = <String, BankData>{
    "CMBC": BankData(
        key: 'CMBC',
        name: '中国民生银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/CMBC.png'),
    "SPABANK": BankData(
        key: 'SPABANK',
        name: '平安银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/SPABANK.png'),
    "CMB": BankData(
        key: 'CMB',
        name: '招商银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/CMB.png'),
    "CIB": BankData(
        key: 'CIB',
        name: '兴业银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/CIB.png'),
    "GDB": BankData(
        key: 'GDB',
        name: '广发银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/GDB.png'),
    "EGBANK": BankData(
        key: 'EGBANK',
        name: '恒丰银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/EGBANK.png'),
    "ZSBANK": BankData(
        key: 'ZSBANK',
        name: '浙商银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/ZSBANK.png'),
    "BOHAIB": BankData(
        key: 'BOHAIB',
        name: '渤海银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/BOHAIB.png'),
    "SPDB": BankData(
        key: 'SPDB',
        name: '上海浦东发展银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/SPDB.png'),
    "HXB": BankData(
        key: 'HXB',
        name: '华夏银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/HXB.png'),
    "CEB": BankData(
        key: 'CEB',
        name: '中国光大银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/CEB.png'),
    "CITIC": BankData(
        key: 'CITIC',
        name: '中信银行',
        logo: 'assets/keep_accounts/bank/gfzsyyh/CITIC.png')
  };
  static Map<String, BankData> gydxsyyh = <String, BankData>{
    "CCB": BankData(
        key: 'CCB',
        name: '建设银行',
        logo: 'assets/keep_accounts/bank/gydxsyyh/CCB.png'),
    "ICBC": BankData(
        key: 'ICBC',
        name: '中国工商银行',
        logo: 'assets/keep_accounts/bank/gydxsyyh/ICBC.png'),
    "ABC": BankData(
        key: 'ABC',
        name: '中国农业银行',
        logo: 'assets/keep_accounts/bank/gydxsyyh/ABC.png'),
    "COMM": BankData(
        key: 'COMM',
        name: '交通银行',
        logo: 'assets/keep_accounts/bank/gydxsyyh/COMM.png'),
    "PSBC": BankData(
        key: 'PSBC',
        name: '中国邮政储蓄银行',
        logo: 'assets/keep_accounts/bank/gydxsyyh/PSBC.png'),
    "BOC": BankData(
        key: 'BOC',
        name: '中国银行',
        logo: 'assets/keep_accounts/bank/gydxsyyh/BOC.png')
  };
  static Map<String, BankData> wzfryh = <String, BankData>{
    "BOSH": BankData(
        key: 'BOSH',
        name: '新韩银行',
        logo: 'assets/keep_accounts/bank/wzfryh/BOSH.png'),
    "FLBSDBANK": BankData(
        key: 'FLBSDBANK',
        name: '菲律宾首都银行',
        logo: 'assets/keep_accounts/bank/wzfryh/FLBSDBANK.png'),
    "FGXYBANK": BankData(
        key: 'FGXYBANK',
        name: '法国兴业银行',
        logo: 'assets/keep_accounts/bank/wzfryh/FGXYBANK.png'),
    "SMBC": BankData(
        key: 'SMBC',
        name: '三井住友银行',
        logo: 'assets/keep_accounts/bank/wzfryh/SMBC.png'),
    "DYZBANK": BankData(
        key: 'DYZBANK',
        name: '德意志银行',
        logo: 'assets/keep_accounts/bank/wzfryh/DYZBANK.png'),
    "HGGMBANK": BankData(
        key: 'HGGMBANK',
        name: '韩国国民银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HGGMBANK.png'),
    "RSBANK": BankData(
        key: 'RSBANK',
        name: '瑞士银行',
        logo: 'assets/keep_accounts/bank/wzfryh/RSBANK.png'),
    "PGBANK": BankData(
        key: 'PGBANK',
        name: '盘谷银行',
        logo: 'assets/keep_accounts/bank/wzfryh/PGBANK.png'),
    "KBANK": BankData(
        key: 'KBANK',
        name: '开泰银行',
        logo: 'assets/keep_accounts/bank/wzfryh/KBANK.png'),
    "HSBANK": BankData(
        key: 'HSBANK',
        name: '华商银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HSBANK.png'),
    "DXBANK": BankData(
        key: 'DXBANK',
        name: '大新银行',
        logo: 'assets/keep_accounts/bank/wzfryh/DXBANK.png'),
    "FGBLBANK": BankData(
        key: 'FGBLBANK',
        name: '法国巴黎银行',
        logo: 'assets/keep_accounts/bank/wzfryh/FGBLBANK.png'),
    "HKBEA": BankData(
        key: 'HKBEA',
        name: '东亚银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HKBEA.png'),
    "ANZ": BankData(
        key: 'ANZ',
        name: '澳大利亚和新西兰银行',
        logo: 'assets/keep_accounts/bank/wzfryh/ANZ.png'),
    "SCB": BankData(
        key: 'SCB',
        name: '渣打银行',
        logo: 'assets/keep_accounts/bank/wzfryh/SCB.png'),
    "TWYSBANK": BankData(
        key: 'TWYSBANK',
        name: '台湾玉山银行',
        logo: 'assets/keep_accounts/bank/wzfryh/TWYSBANK.png'),
    "ZXBANK": BankData(
        key: 'ZXBANK',
        name: '正信银行',
        logo: 'assets/keep_accounts/bank/wzfryh/ZXBANK.png'),
    "ZXYXGJBANK": BankData(
        key: 'ZXYXGJBANK',
        name: '中信银行国际',
        logo: 'assets/keep_accounts/bank/wzfryh/ZXYXGJBANK.png'),
    "FGDFHLBANK": BankData(
        key: 'FGDFHLBANK',
        name: '法国东方汇理银行',
        logo: 'assets/keep_accounts/bank/wzfryh/FGDFHLBANK.png'),
    "PFGGBANK": BankData(
        key: 'PFGGBANK',
        name: '浦发硅谷银行',
        logo: 'assets/keep_accounts/bank/wzfryh/PFGGBANK.png'),
    "HANABANK": BankData(
        key: 'HANABANK',
        name: '韩亚银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HANABANK.png'),
    "MGSDLGJBANK": BankData(
        key: 'MGSDLGJBANK',
        name: '摩根士丹利国际银行',
        logo: 'assets/keep_accounts/bank/wzfryh/MGSDLGJBANK.png'),
    "HGYLBANK": BankData(
        key: 'HGYLBANK',
        name: '韩国友利银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HGYLBANK.png'),
    "NCB": BankData(
        key: 'NCB',
        name: '南洋商业银行',
        logo: 'assets/keep_accounts/bank/wzfryh/NCB.png'),
    "MGDTBANK": BankData(
        key: 'MGDTBANK',
        name: '摩根大通银行',
        logo: 'assets/keep_accounts/bank/wzfryh/MGDTBANK.png'),
    "HSBANK": BankData(
        key: 'HSBANK',
        name: '恒生银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HSBANK.png'),
    "DHBANK": BankData(
        key: 'DHBANK',
        name: '大华银行',
        logo: 'assets/keep_accounts/bank/wzfryh/DHBANK.png'),
    "XLSYBANK": BankData(
        key: 'XLSYBANK',
        name: '新联商业银行',
        logo: 'assets/keep_accounts/bank/wzfryh/XLSYBANK.png'),
    "YFBANK": BankData(
        key: 'YFBANK',
        name: '永丰银行',
        logo: 'assets/keep_accounts/bank/wzfryh/YFBANK.png'),
    "GTSHBANK": BankData(
        key: 'GTSHBANK',
        name: '国泰世华银行',
        logo: 'assets/keep_accounts/bank/wzfryh/GTSHBANK.png'),
    "HQBANK": BankData(
        key: 'HQBANK',
        name: '花旗银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HQBANK.png'),
    "HMBANK": BankData(
        key: 'HMBANK',
        name: '华美银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HMBANK.png'),
    "HGQYBANK": BankData(
        key: 'HGQYBANK',
        name: '韩国企业银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HGQYBANK.png'),
    "HQYHBANK": BankData(
        key: 'HQYHBANK',
        name: '华侨永亨银行',
        logo: 'assets/keep_accounts/bank/wzfryh/HQYHBANK.png'),
    "FBHYBANK": BankData(
        key: 'FBHYBANK',
        name: '富邦华一银行',
        logo: 'assets/keep_accounts/bank/wzfryh/FBHYBANK.png'),
    "ZYSYBANK": BankData(
        key: 'ZYSYBANK',
        name: '彰银商业银行',
        logo: 'assets/keep_accounts/bank/wzfryh/ZYSYBANK.png'),
    "RSSYBANK": BankData(
        key: 'RSSYBANK',
        name: '瑞穗实业银行',
        logo: 'assets/keep_accounts/bank/wzfryh/RSSYBANK.png'),
    "DBSCN": BankData(
        key: 'DBSCN',
        name: '星展银行',
        logo: 'assets/keep_accounts/bank/wzfryh/DBSCN.png'),
    "MTLEBANK": BankData(
        key: 'MTLEBANK',
        name: '蒙特利尔银行',
        logo: 'assets/keep_accounts/bank/wzfryh/MTLEBANK.png')
  };
}
